### ISSUE TITLE
Plugin support in Grafana

### ISSUE THREAD

**Issue by luvpreetsingh** [tkurki/grafana-track-map#2]
How do we add this plugin in Grafana dashboard ?
I don't see this plugin in grafana's available plugins.

Please give a detailed explanation on how this plugin can be used in grafana dashboard.

Also, what tags and fields we need to have compulsory in Influxdb database to use this plugin ?

**Comment by tkurki** [comment]
I added a bit more instructions. Sorry, I can't offer much in the way of support here, as this is a side project of a side project to me.
