### ISSUE TITLE
No crosshair / current position

### ISSUE THREAD

**Issue by wolfff** [tkurki/grafana-track-map#4]
I got the map added to my dashboard running with Grafana v4.3.2 (commit: ed4d170)
The map displays the values from the geohash as a track, and when I restrict the time beeing displayed, I see that the map shows the correct location(s).
However when I move the synchronized cross-hairs around, I see them in all panels, except the map.
Any advice?

**Comment by tkurki** [comment]
Not really. That works for me - maybe something has changed in Grafana?

The relevant code is at https://github.com/tkurki/grafana-track-map/blob/master/src/clock_ctrl.js#L24
