### ISSUE TITLE
Purpose of value?

### ISSUE THREAD

**Issue by wolfff** [tkurki/grafana-track-map#5]
What is the purpose of the "value" I select in the query? Does it just serves as the selector where a point is created on the map (if the expression results into some true)? 
Would it be possible to style (color or size) the map point based on the respective value?

**Comment by tkurki** [comment]
My original idea was to color the track based on the value. Then I changed to using a continuous line with a single color and never removed the value.

It would be fairly easy to plot the positions as points, color depending on the value.
