### ISSUE TITLE
Unable to plot (data[0] is undefined)

### ISSUE THREAD

**Issue by luvpreetsingh** [tkurki/grafana-track-map#8]
I am performing this on ubuntu 16.04, just installed it today(latest version).

I choose the map panel, 

![image 2](https://user-images.githubusercontent.com/23127804/28361917-0cc77a64-6c98-11e7-997a-2e96027ab9f5.jpg)

The moment I select this map panel, I get this error on the right corner, 
![image 1](https://user-images.githubusercontent.com/23127804/28361939-246a275c-6c98-11e7-952f-e888d38d913d.jpg)

I will show my data which I want to plot, 

    > select * from "second-test3"
    name: second-test3
    time                geohash      latitude  longitude reported_time
    ----                -------      --------  --------- -------------
    1500377922901712970 tdr1qtb79vqs 12.908192 77.629822 2017-07-17 13:08:45.008531+00:00 
    1500377923013524579 tdr1qtb79vqs 12.908192 77.629822 2017-07-17 13:08:21.590246+00:00
    1500377923163653648 tdr1qtb79vqs 12.908192 77.629822 2017-07-17 13:08:09.669630+00:00

I have the geohash field. This is my query, 

`SELECT "geohash"  as geohash  FROM "second-test3" `

Can you assist me and tell me what is wrong ?

**Comment by tkurki** [comment]
ef7fba5366cc66932babf2a38d47b0ea144f384f

I have abandoned this project, feel free to fork & assume ownership.
