### ISSUE TITLE
not working with grafana 4.6.2

### ISSUE THREAD

**Issue by oliv3** [tkurki/grafana-track-map#9]
Hi, I installed the plugin, restarted grafana.
The plugin appears in the plugins list but will not show up when adding a new panel.
This is grafana 4.6.2, the plugin works with 4.5.2
Thanks,

**Comment by tkurki** [comment]
Sorry, I have abandoned this project, feel free to fork & assume ownship.

ef7fba5366cc66932babf2a38d47b0ea144f384f
